package mineitdown

// Constants
WINDOW_SIZE :: 1000
GRID_WIDTH :: 7
CELL_SIZE :: 16
CANVAS_SIZE :: GRID_WIDTH * CELL_SIZE
MAX_GRID_CELLS :: GRID_WIDTH * GRID_WIDTH
GRID_LINE_WIDTH :: 1.5
GRID_LINE_OFFSET :: GRID_LINE_WIDTH / 2
BOARD_OFFSET_X :: GRID_LINE_OFFSET
BOARD_OFFSET_Y :: GRID_LINE_OFFSET
